services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: user-management-backend

    ports:
      - "8080:8080"

    volumes:
      - .:/app

    restart: always

  postgres:
    image: postgres:17

    container_name: user-management-db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: usermanagement

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile

    container_name: user-management-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: always

volumes:
  postgres_data: